name: FullStack CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: cd backend && npm ci && cd -
    - run: cd backend && npm test && cd -
      env:
        CI: true

  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: cd frontend && npm ci && cd -
    - run: cd frontend && npx jest --ci && cd -
      env:
        CI: true
