name: Test CI
image: node:alpine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: cd frontend
    - run: npm ci
    - run: npx jest --ci
    - run: cd -
      env:
        CI: true
